### ISSUE TITLE
download_crunchyroll_apk 404 response

### ISSUE THREAD

**Issue by Aughen** [Centulus/BasicAuthFetch#1]
Hello, 

I was able to get this installed and going.. trying to get my Crunchy Roll working again 

I am getting this when i run the python code 

=== CRUNCHYROLL CREDENTIAL EXTRACTOR ===
This tool will download, decompile, and extract credentials from Crunchyroll APK
==================================================
=== PHASE 1: DOWNLOADING CRUNCHYROLL APK ===
Fetching Crunchyroll download page...
Failed to access download page. Status code: 403
Failed to download the APK. Aborting.

any ideas?

**Comment by Centulus** [comment]
Should be fixed... the issue came from the APK download API now being behind Cloudflare, which was blocking the request. I replaced the `requests` calls with `cloudscraper`. let me know if it now goes through on your side.

**Comment by Aughen** [comment]
Sorry for the delay—I didn’t see your response right away. I used the latest instructions you provided and installed the most recent versions of beautifulsoup4 and cloudscraper using pip, but I’m still encountering 403 errors.
Here are the relevant logs:

Python 3.13.3 (tags/v3.13.3:6280bb5, Apr 8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)] on win32

============ RESTART: B:\Pii\CrunchyRoll\BasicAuthFetch-main\main.py ===========
=== CRUNCHYROLL CREDENTIAL EXTRACTOR ===
This tool will download, decompile, and extract credentials from Crunchyroll APK
==================================================
=== PHASE 1: DOWNLOADING CRUNCHYROLL APK ===
Fetching Crunchyroll download page...
Failed to access download page. Status code: 403
Failed to download the APK. Aborting.

Let me know if there's anything else I should try or if you're seeing something I missed. Thanks again for your help.

**Comment by Centulus** [comment]
I just updated again and it's working fine on my end right now
Also added the token checker 

Let me know what you're seeing on your side

**Comment by Centulus** [comment]
I’ve added another provider (ApkCombo) to reduce the chances of failure. As a fallback, you can use `--manual` and provide a pre-downloaded XAPK. Marking this issue as closed.
